mysite/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register_company", views.register_company, name="register_company"),
    path("private_leasing", views.private_leasing, name="private_leasing"),
    path("business_leasing", views.business_leasing, name="business_leasing"),
    path("contact", views.contact, name="contact"),
    path("private_cars/<int:car_id>", views.private_car, name="private_cars"),
    path("business_cars/<int:car_id>", views.business_car, name="business_cars"),
    path("profile_page", views.profile_page, name="profile_page"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("register", views.register, name="register"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('main.urls')),
    path('admin/', admin.site.urls),
]

mysite/main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import widgets, ModelForm
from django.forms.widgets import TextInput, PasswordInput, DateInput
from .models import *


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(
        attrs={'placeholder': 'Password'}))


class RegisterProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profilePhoneNumber', 'profileCprNumber',
                  'profileAddress', 'profileCity', 'profilePostalCode')


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name",
                  "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_active = True
        if commit:
            user.save()
        return user


class ContactForm(forms.Form):
    your_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'rows': '10', 'style': 'resize: none; min-height: 100px'}), required=True)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profilePhoneNumber', 'profileCprNumber',
                  'profileAddress', 'profileCity', 'profilePostalCode')


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('contactPerson', 'companyName', 'companyAddress', 'companyCity',
                  'companyPostalCode', 'cvrNumber')


class PrivateLeasingForm(forms.Form):
    start_date = forms.DateField(required=True, widget=DateInput())
    end_date = forms.DateField(required=True)
    down_payment = forms.DecimalField(required=True)
    monthly_price = forms.DecimalField(required=True)
    miles_per_year = forms.IntegerField(required=True)
    car = forms.CharField(required=True)
    customer = forms.CharField(required=True)


class BusinessLeasingForm(forms.Form):
    start_date = forms.DateField(required=True, widget=DateInput())
    end_date = forms.DateField(required=True)
    down_payment = forms.DecimalField(required=True)
    monthly_price = forms.DecimalField(required=True)
    miles_per_year = forms.IntegerField(required=True)
    car = forms.CharField(required=True)
    company = forms.CharField()

mysite/main/views.py
from django.shortcuts import render, redirect
from .models import Car, User, Profile, PrivateLease, CompanyLease, Company
from .forms import LoginForm, NewUserForm, RegisterProfileForm, UserForm, ProfileForm, ContactForm, CompanyForm, PrivateLeasingForm, BusinessLeasingForm
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.urls import reverse
from django.core.mail import send_mail, BadHeaderError
from datetime import date

# Create your views here.


def homepage(request):
    carsForPrivate = Car.objects.filter(carReadyForPrivateLeasing=True).order_by('-carNewPrice')[:4]
    carsForCompany = Car.objects.filter(carReadyForBusinessLeasing=True).order_by('-carNewPrice')[:4]
    print(carsForPrivate)
    print(carsForCompany)
    return render(request=request,
                  template_name='main/home.html',
                  context={'loginForm': LoginForm,
                           'username': request.user.username,
                           'user_id': request.user.id,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm,
                           'privateCars': carsForPrivate,
                           'companyCars': carsForCompany,
                           })


def private_leasing(request):
    return render(request=request,
                  template_name='main/private_leasing.html',
                  context={'cars': Car.objects.filter(carReadyForPrivateLeasing=True),
                           'loginForm': LoginForm,
                           'username': request.user.username,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm, })


def business_leasing(request):
    return render(request=request,
                  template_name='main/business_leasing.html',
                  context={'cars': Car.objects.filter(carReadyForBusinessLeasing=True),
                           'loginForm': LoginForm,
                           'username': request.user.username,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm, })


def contact(request):
    if request.method == 'GET':
        contact_form = ContactForm()
    else:
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            subject = contact_form.cleaned_data['subject']
            your_email = contact_form.cleaned_data['from_email']
            message = contact_form.cleaned_data['message']
            try:
                send_mail(subject, message, your_email,
                          ['mort333c@edu.sde.dk'])
            except BadHeaderError:
                for msg in contact_form.error_messages:
                    messages.error(
                        request, f"{msg}: {contact_form.error_messages[msg]}")
    return render(request=request,
                  template_name='main/contact.html',
                  context={'loginForm': LoginForm,
                           'username': request.user.username,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm,
                           'contact_form': contact_form})


def business_car(request, car_id):
    car = Car.objects.get(id=car_id)
    currentUser = request.user
    customerCompanies = Company.objects.filter(contactPerson=currentUser)
    today = date.today()
    todayFormatted = today.strftime("%Y-%m-%d")
    if request.method == 'POST':
        businessLeasingForm = BusinessLeasingForm(request.POST)
        print(businessLeasingForm.errors.as_data())
        if businessLeasingForm.is_valid():
            leaseStartDate = businessLeasingForm.cleaned_data['start_date']
            leaseEndDate = businessLeasingForm.cleaned_data['end_date']
            leaseDownpayment = businessLeasingForm.cleaned_data['down_payment']
            leaseMonthlyPrice = businessLeasingForm.cleaned_data['monthly_price']
            leaseMilesPerYear = businessLeasingForm.cleaned_data['miles_per_year']
            leaseCar = car
            print(businessLeasingForm.cleaned_data['company'])
            leaseCompany = Company.objects.get(id=businessLeasingForm.cleaned_data['company'])

            newBusinessLease = CompanyLease(leaseStartDate=leaseStartDate, leaseEndDate=leaseEndDate, leaseDownpayment=leaseDownpayment,
                                            leaseMonthlyPrice=leaseMonthlyPrice, leaseMilesPerYear=leaseMilesPerYear, leaseCar=leaseCar, leaseCustomerCompany=leaseCompany)

            newBusinessLease.save()

            car.carCurrentlyLeased = True
            car.save()

            return redirect("main:profile_page")

    return render(request=request,
                  template_name='main/businesscars/car_details.html',
                  context={'car': car,
                           'loginForm': LoginForm,
                           'username': request.user.username,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm,
                           'businessLeasingForm': BusinessLeasingForm,
                           'today': todayFormatted,
                           'current_user': currentUser,
                           'customer_companies': customerCompanies})


def private_car(request, car_id):
    car = Car.objects.get(id=car_id)
    currentUser = request.user
    today = date.today()
    todayFormatted = today.strftime("%Y-%m-%d")
    if request.method == 'POST':
        privateLeasingForm = PrivateLeasingForm(request.POST)
        print(privateLeasingForm.errors.as_data())
        if privateLeasingForm.is_valid():
            leaseStartDate = privateLeasingForm.cleaned_data['start_date']
            leaseEndDate = privateLeasingForm.cleaned_data['end_date']
            leaseDownpayment = privateLeasingForm.cleaned_data['down_payment']
            leaseMonthlyPrice = privateLeasingForm.cleaned_data['monthly_price']
            leaseMilesPerYear = privateLeasingForm.cleaned_data['miles_per_year']
            leaseCar = car
            leaseCustomer = currentUser

            newPrivateLease = PrivateLease(leaseStartDate=leaseStartDate, leaseEndDate=leaseEndDate, leaseDownpayment=leaseDownpayment,
                                           leaseMonthlyPrice=leaseMonthlyPrice, leaseMilesPerYear=leaseMilesPerYear, leaseCar=leaseCar, leaseCustomer=leaseCustomer)

            newPrivateLease.save()

            car.carCurrentlyLeased = True
            car.save()

            return redirect("main:profile_page")

    return render(request=request,
                  template_name='main/privatecars/car_details.html',
                  context={'car': car,
                           'loginForm': LoginForm,
                           'username': request.user.username,
                           'registerUser': NewUserForm,
                           'registerProfile': RegisterProfileForm,
                           'privateLeasingForm': PrivateLeasingForm,
                           'today': todayFormatted,
                           'current_user': currentUser})


def profile_page(request):
    userCompanies = []
    if request.method == 'POST':
        # user = User.objects.get(id=user_id)
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        user_form.save()
        profile_form.save()
    elif request.method == 'GET':
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
        userCompanies = Company.objects.filter(contactPerson=request.user.id)
    return render(request=request,
                  template_name='main/profile_page.html',
                  context={'user_form': user_form,
                           'profile_form': profile_form,
                           'privateLeases': PrivateLease.objects.filter(leaseCustomer=request.user),
                           'companyLeases': CompanyLease.objects.filter(leaseCustomerCompany__in=userCompanies),
                           'userCompanies': userCompanies,
                           'companyForm': CompanyForm})


def register_company(request):
    form = CompanyForm(request.POST)
    # print(form.errors.as_text())
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        else:
            print(form.errors.as_text())
            messages.error(request, form.errors.as_data())

    return redirect('main:profile_page')


def login_request(request):
    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Logged in: {username}")
                return redirect('/')

    messages.error(request,
                   f"login failed, the login details provided wrong")
    return redirect('main:homepage')


def logout_request(request):
    logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect('main:homepage')


def register(request):
    if request.method == 'POST':
        userForm = NewUserForm(request.POST)
        profileForm = RegisterProfileForm(request.POST)
        print(userForm.errors.as_data())
        if userForm.is_valid() and profileForm.is_valid():
            user = userForm.save()
            user.profile.profilePhoneNumber = request.POST['profilePhoneNumber']

mysite/main/templates/main/business_leasing.html
{% extends 'main/header.html' %}
{% load static %}
{% block 'content' %}
<div class="container">
    <div class="center-align"><h4>Options for business leasing</h4></div>
    <div class="row">
        {% for car in cars %}
        {% if car.carCurrentlyLeased == False %}
        <div class="col s6 m3">
            <div class="card">
                <div class="card-image">
                    {% for carImage in car.carImage.all %}
                        {% if forloop.first %}
                        <img src="{{carImage.image.url}}">
                        {% endif %}
                    {% endfor %}
                    

                </div>
                <div class="card-content">
                    <span class="card-title">{{car.model.modelBrand}} {{car.model.modelName}}</span>
                </div>
                <div class="card-action">
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-tachometer-alt"></i> {{car.milage}} Miles</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="far fa-calendar-alt"></i> {{car.model.modelYear}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-gas-pump"></i> {{car.model.modelFuelType}}</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="fas fa-horse-head"></i> {{car.model.modelPower}} BHP</p>
                        </div>
                    </div>
                    <a class="btn waves-effect waves-light red lighten-2" href="{% url 'main:business_cars' car.id %}">More information</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock 'content' %}

mysite/main/templates/main/header.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>A/M Leasing</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://kit.fontawesome.com/c16b59f4d0.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>
    <body>
        <header>
            <nav>
                <div class="nav-wrapper">
                    <a href="{% url 'main:homepage' %}" class="brand-logo"><img id="navlogo" src="{% static 'img/a-m_leasing.png' %}"></a>
                    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a class="waves-effect waves-light" href="{% url 'main:homepage' %}"><i class="fas fa-home"></i> Home</a></li>
                        <li><a class="waves-effect waves-light" href="{% url 'main:private_leasing' %}"><i class="fas fa-car-side"></i> Private Leasing</a></li>
                        <li><a class="waves-effect waves-light" href="{% url 'main:business_leasing' %}"><i class="fas fa-truck"></i> Business Leasing</a></li>
                        <li><a class="waves-effect waves-light" href="{% url 'main:contact' %}"><i class="fas fa-phone"></i> Contact Us</a></li>
                        {% if user.is_authenticated and user.is_superuser %}
                        <li><a class="waves-effect waves-light" href="admin"><i class="fas fa-user"></i> {{user.username|capfirst}}</a></li>
                        <li><a class="waves-effect waves-light" href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                        {% elif user.is_authenticated %}
                        <li><a class="waves-effect waves-light" href="{% url 'main:profile_page' %}"><i class="fas fa-user"></i> {{user.username|capfirst}}</a></li>
                        <li><a class="waves-effect waves-light" href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                        {% else %}
                        <li><a class="waves-effect waves-light modal-trigger" href="#loginModal"><i class="fas fa-sign-in-alt"></i> Log In</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <ul class="sidenav" id="mobile-demo">
                <li><a class="waves-effect waves-light" href="{% url 'main:homepage' %}"><i class="fas fa-home"></i> Home</a></li>
                <li><a class="waves-effect waves-light" href="{% url 'main:private_leasing' %}"><i class="fas fa-car-side"></i> Private Leasing</a></li>
                <li><a class="waves-effect waves-light" href="{% url 'main:business_leasing' %}"><i class="fas fa-truck"></i> Business Leasing</a></li>
                <li><a class="waves-effect waves-light" href="{% url 'main:contact' %}"><i class="fas fa-phone"></i> Contact Us</a></li>
                {% if user.is_authenticated and user.is_superuser %}
                <li><a class="waves-effect waves-light" href="admin"><i class="fas fa-user"></i> {{user.username|capfirst}}</a></li>
                <li><a class="waves-effect waves-light" href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                {% elif user.is_authenticated %}
                <li><a class="waves-effect waves-light" href="{% url 'main:profile_page' %}"><i class="fas fa-user"></i> {{user.username|capfirst}}</a></li>
                <li><a class="waves-effect waves-light" href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
                {% else %}
                <li><a class="waves-effect waves-light modal-trigger" href="#loginModal"><i class="fas fa-sign-in-alt"></i> Log In</a></li>
                {% endif %}
            </ul>

            <div id="loginModal" class="modal">
                <div class="modal-content">
                    <form id="login" class="" method="POST" action="/login">
                        <h4>Login</h4>
                        {% csrf_token %}
                        {{loginForm.as_p}}
                        <div class="col s12">
                            <button class="waves-effect waves-light btn red lighten-2" type="submit">Login</button>
                            <p class="center">Not registered? <a class="modal-trigger"href="#signupModal">Create an account</a></p>
                        </div>
                    </form>
                </div>
            </div>
            <div id="signupModal" class="modal">
                <div class="modal-content">
                    <form id="signupModal" class="" method="POST" action="/register">
                        <h4>Sign Up</h4>
                        {% csrf_token %}
                        {{registerUser.as_p}}
                        {{registerProfile.as_p}}
                        <div class="col s12">
                            <button class="waves-effect waves-light btn red lighten-2" type="submit">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Modal trigger -->
            <script>$(document).ready(function(){$('.modal').modal();});</script>
        </header>
        <main>
            {% if messages %}
                {% for message in messages %}
                    <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:3000});</script>
                {% endfor %}
            {% endif %}
            {% block 'content' %}
            {% endblock 'content' %}

        </main>
        <footer class="page-footer">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text">A/M Leasing</h5>
                        <p class="grey-text text-lighten-4">Dronningensgade 107b st.t.v
                        </p>
                        <p class="grey-text text-lighten-4">5000 Odense C, Denmark
                        </p>
                        <p class="grey-text text-lighten-4">+45 67 68 91 02
                        </p>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    © 2021 A/M Leasing
                </div>
            </div>
        </footer>
        <script>
        $(document).ready(function() { $("#navlogo").css("height", $(".nav-wrapper").height()); });
        $(document).ready(function(){
            $('.sidenav').sidenav();
        });
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

mysite/main/templates/main/home.html
{% extends 'main/header.html' %}
{% load static %}
{% block 'content' %}
<div class="slider">
    <ul class="slides">
        <li>
            <img class="responsive-img" src="{% static '/img/banner/handsome-man-standing-in-front-of-black-car-and-presenting-it-PXBAXB.jpg' %}"> <!-- random image -->
            <div class="caption center-align">
                <h3>We have private leasing</h3>
                <a href="private_leasing" class="waves-effect waves-light red lighten-2 btn">See our assortment of cars</a>
            </div>
        </li>
        <li>
            <img class="responsive-img" src="{% static 'img/banner/smiling-young-man-standing-front-car-talking-smartphone_23-2147937294.jpg' %}"> <!-- random image -->
            <div class="caption left-align">
                <h3>Leasing for your business?</h3>
                <a href="business_leasing" class="waves-effect waves-light red lighten-2 btn">Check out our assortment!</a>
            </div>
        </li>
        <li>
            <img class="responsive-img" src="{% static 'img/banner/depositphotos_188823644-stock-photo-man-standing-near-his-car.jpg' %}"> <!-- random image -->
            <div class="caption right-align">
                <h3>Do you have questions regarding leasing?</h3>
                <a href="contact" class="waves-effect waves-light red lighten-2 btn">Contact Us!</a>
            </div>
        </li>
    </ul>
</div>
<div class="container">
    <h4 style="display: inline-block;">Private Leasing Options</h4><a style="display: inline-block;" href="{% url 'main:private_leasing' %}" class="right-align waves-effect red lighten-2 waves-light btn"><i class="fas fa-car"></i></a>
    <div class="row">
        {% for car in privateCars %}
        {% if car.carCurrentlyLeased == False %}
        <div class="col s6 m3">
            <div class="card">
                <div class="card-image">
                    {% for carImage in car.carImage.all %}
                        {% if forloop.first %}
                        <img src="{{carImage.image.url}}">
                        {% endif %}
                    {% endfor %}
                    

                </div>
                <div class="card-content">
                    <span class="card-title">{{car.model.modelBrand}} {{car.model.modelName}}</span>
                </div>
                <div class="card-action">
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-tachometer-alt"></i> {{car.milage}} Miles</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="far fa-calendar-alt"></i> {{car.model.modelYear}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-gas-pump"></i> {{car.model.modelFuelType}}</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="fas fa-horse-head"></i> {{car.model.modelPower}} BHP</p>
                        </div>
                    </div>
                    <a class="btn waves-effect waves-light red lighten-2" href="{% url 'main:private_cars' car.id %}">More information</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <h4 style="display: inline-block;">Business Leasing Options</h4><a style="display: inline-block;" href="{% url 'main:business_leasing' %}" class="waves-effect red lighten-2 waves-light btn"><i class="fas fa-car"></i></a>
    <div class="row">
        {% for car in companyCars %}
        {% if car.carCurrentlyLeased == False %}
        <div class="col s6 m3">
            <div class="card">
                <div class="card-image">
                    {% for carImage in car.carImage.all %}
                        {% if forloop.first %}
                        <img src="{{carImage.image.url}}">
                        {% endif %}
                    {% endfor %}
                    

                </div>
                <div class="card-content">
                    <span class="card-title">{{car.model.modelBrand}} {{car.model.modelName}}</span>
                </div>
                <div class="card-action">
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-tachometer-alt"></i> {{car.milage}} Miles</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="far fa-calendar-alt"></i> {{car.model.modelYear}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-gas-pump"></i> {{car.model.modelFuelType}}</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="fas fa-horse-head"></i> {{car.model.modelPower}} BHP</p>
                        </div>
                    </div>
                    <a class="btn waves-effect waves-light red lighten-2" href="{% url 'main:business_cars' car.id %}">More information</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
<script>
  $(document).ready(function(){
    $('.slider').slider()
  })
</script>
{% endblock 'content' %}

mysite/main/templates/main/private_leasing.html
{% extends 'main/header.html' %}
{% load static %}
{% block 'content' %}
<div class="container">
    <div class="center-align"><h4>Options for private leasing</h4></div>
    <div class="row">
        {% for car in cars %}
        {% if car.carCurrentlyLeased == False %}
        <div class="col s6 m3">
            <div class="card">
                <div class="card-image">
                    {% for carImage in car.carImage.all %}
                        {% if forloop.first %}
                        <img src="{{carImage.image.url}}">
                        {% endif %}
                    {% endfor %}
                    

                </div>
                <div class="card-content">
                    <span class="card-title">{{car.model.modelBrand}} {{car.model.modelName}}</span>
                </div>
                <div class="card-action">
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-tachometer-alt"></i> {{car.milage}} Miles</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="far fa-calendar-alt"></i> {{car.model.modelYear}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12 m6">
                            <p><i class="fas fa-gas-pump"></i> {{car.model.modelFuelType}}</p>
                        </div>
                        <div class="col s12 m6">
                            <p><i class="fas fa-horse-head"></i> {{car.model.modelPower}} BHP</p>
                        </div>
                    </div>
                    <a class="btn waves-effect waves-light red lighten-2" href="{% url 'main:private_cars' car.id %}">More information</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock 'content' %}